# Generated by Django 5.0.1 on 2024-01-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='betmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='betmodel',
            name='second_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='betmodel',
            name='tird_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
