# Generated by Django 5.0.1 on 2024-01-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_enrollmodel_end_data_walletmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollModel',
        ),
    ]
