# Generated by Django 5.0.1 on 2024-01-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_enrollmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='betmodel',
            name='max_enroll',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
