# Generated by Django 5.0.1 on 2024-01-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betslotmodel',
            name='user',
        ),
    ]
