# Generated by Django 5.0.1 on 2024-01-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_remove_enrollmodel_bet'),
        ('home', '0006_betmodel_max_enroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='enrollmodel',
            name='bet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.betmodel'),
        ),
    ]
