# Generated by Django 5.0.1 on 2024-01-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_enrollmodel_user'),
        ('home', '0007_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmodel',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.slot'),
        ),
        migrations.RenameField(
            model_name='enrollmodel',
            old_name='created',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='enrollmodel',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BetSlotModel',
        ),
    ]
